* dotfiles: Archivos de configuración de mis instalaciones de Debian.

** En la carpeta i3 están las configuraciones de i3 e i3blocks.
   La configuración de i3 va en ~/.config/i3 y la de i3blocks en .config/i3blocks
** El input.conf es el fichero de configuración de mpv.

** En oldemacs está la antigua programación literaria en org-mode que tenía antes de Prelude.
   TODO: Creo que esto debería mergearlo con la que uso ahora o eliminarla.
** El emacs.el es la configuración de Emacs Prelude que usaba durante mi etapa con Prelude.
   TODO: Debería reorganizarlo y meter esto en una carpeta, ya que ahora mismo no lo uso.
** En newemacs estoy probando la nueva configuración literaria que uso actualmente.

** Estado de la autoinstalación de Emacs:

Ahora mismo se instala de forma semiautomática mi configuración. Me queda por resolver lo de que me pide que exista el archivo ~/Nextcloud/Documents/horario.txt, que además tiene que contener lo siguiente:

 ; -*-Org-*-

Además no se instalan todos los paquetes de forma automática, me tengo que ir al init.el y ejecutar

(package-refresh-contents)
(package-install-selected-packages)

Y para que no de error la config de emms también tengo que tener una canción en ~/Música.

También debería borrar de emacs-literario.org la parte de configuración de paquetes y autoinstalación y moverla al init.el
