* dotfiles: Archivos de configuración de mis programas de Debian.

** Cómo replicar mi configuración
En cada subapartado siguiente se explica dónde colocar los correspondientes ficheros.

*** En la carpeta i3 están las configuraciones de i3 e i3blocks.
   La configuración de i3 va en ~/.config/i3 y la de i3blocks en .config/i3blocks. Para instalar i3blocks en un nuevo ordenador, hacer un git clone de "https://github.com/vivien/i3blocks-contrib" y renombrar el repo a i3blocks y ponerlo en ~/.config/i3blocks

*** El input.conf es el fichero de configuración de mpv. 
Va en ~/.config/mpv/input.conf

*** Los ficheros init.el, emacs-literario.org y emacs-literario.el son los archivos de configuración de Emacs.
     El init.el es el primer archivo que lee Emacs al empezar (donde empieza la magia). Ahí tengo puesto que cargue el archivo emacs-literario.org que se encarga de generar el emacs-literario.el que es donde tengo mi configuración. Para mas información véase el principio del archivo emacs-literario.org.

     Para replicar la configuración de Emacs hay que crear un simlink (por ejemplo desde dired pulsando S, o, estando en ~/.emacs.d/, con =ln -s ~/git/dotfiles/.emacs.d/init.el=) del init.el y del custom.el, desde ~/git/dotfiles/.emacs.d/init.el a ~/.emacs.d/init.el

*** El .bashrc y el .bashrc_aliases son las configuraciones de bash.
     El .bashrc va en ~/.bashrc

*** Fichero alias
    Este fichero contiene los alias que uso para eshell. Debe ir en ~/.emacs.d/eshell/alias
*** Fichero misfunciones.el
    Fichero que contiene las funciones de elisp que he creado.
*** Fichero .offlineimaprc, configuración del correo.
Aquí configuro el programa offlineimap para poder descargarme los correos del servidor correspondiente. Actualmente lo combino con notmuch y el cliente para emacs de notmuch, y así puedo leer el correo en Emacs. La configuración necesaria es tener el .offlineimaprc en ~/.offlineimaprc. Luego ejecutar notmuch y configurarlo con el asistente, y por último hay que ejecutar "notmuch new" cada vez que offlineimap descargue correo. Para ello se puede por ejemplo crear un script en ~/bin/offlineimap-postsync, poner dentro "notmuch new" y luego hacerle "chmod +x". La línea de .offlineimaprc de postcript apunta al script.
*** Estado de la autoinstalación de Emacs:

¡Creo que ya funciona! Ahora mismo si clono el repo en un ordenador se auto-construye toda mi configuración desde cero, pidiendo al usuario que confirme la instalación de paquetes.
