* Por hacer:
** DONE Encontrar una forma de poner los #+BEGIN_SRC emacs-lisp #+END_SRC de forma automática: Se hace con <s y luego TAB (En versiones recientes de Emacs es con C-c C-,)
** TODO Poner las funciones de elisp en un fichero aparte: [[*Scratch][Scratch]], [[*Eshell][Eshell]] (sudeame y la de prot), [[*Puesta de sol][Puesta de sol]], [[*Uso básico][esrinca]], [[*Correo][Correo]], y varias de [[*Elfeed][Elfeed]].
** TODO Autoiniciar offlineimap y autoponer la contraseña
** TODO Poner como tangle las cosas de ~/bin, por ejemplo
#+begin_src shell :tangle ~/bin/offlineimap-postsync
notmuch new
#+end_src
** TODO Tangle condicional para generalizar mi config a otros ordenadores

* Qué está pasando
Mi configuración de Emacs está escrita con el estilo de programación literaria. De esta forma es mucho más fácil ir documentando el código a medida que se va escribiendo.

Para ello se usa el programa "tangle"  para cargar desde el archivo de inicio de emacs tradicional (el init.el) un archivo org (emacs-literario.org) que luego automágicamente se convierte en un emacs-literario.el.

A partir de ahí ya se lee la configuración normal, solo que en vez de estar toda "del tirón" está en bloques (#+BEGIN_SRC emacs-lisp #+END_SRC) que son leídos y transformados adecuadamente para cargarse.

Por tanto para replicar esta configuración se necesitan tener dos archivos (init.el y emacs-literario.org) y los dos en el mismo directorio (típicamente ~/.emacs.d).

** Dependencias
Para que la configuración se pueda crear correctamente hay que instalar una serie de paquetes aparte de Emacs:
*** Notmuch
Programa de indexado y búsqueda de correo.
*** Offlineimap
Sincronización del correo con un servidor.

* Carga de programas externos
Carga de código de programas definidos en otros ficheros
#+begin_src emacs-lisp
  (load-file "~/git/dotfiles/tetritecla.el")
  (load-file "~/git/dotfiles/misfunciones.el")
  (load-file "~/git/dotfiles/mismacros.el")
#+end_src
* Configuración básica
Pequeños ajustes simples.
** Fuentes
Aumento el tamaño de letra en el sobremesa y el MSI para ver mejor.
#+begin_src emacs-lisp
  (if (equal system-name "cpr-GE75-Raider-8SE")
      (set-face-attribute 'default nil :height 150))
  
  (if (equal system-name "elsobremesas")
      (set-face-attribute 'default nil :height 150))
#+end_src
** Iconos
Iconos para dired
#+begin_src emacs-lisp
(add-hook 'dired-mode-hook 'treemacs-icons-dired-mode)
#+end_src
** Arreglos para mis funciones
  Para que funcione bien mi función rat/killydelete suprimo la confirmación al eliminar un búfer con un proceso.
#+begin_src emacs-lisp
    (setq kill-buffer-query-functions (delq 'process-kill-buffer-query-function kill-buffer-query-functions))
#+end_src
** Dashboard
Para mejorar la pantalla de inicio, con dashboard se muestran archivos recientes y más cosas:
#+begin_src emacs-lisp
(dashboard-setup-startup-hook)
(setq dashboard-center-content t)
(setq dashboard-banner-logo-title "¡Bienvenido a GNU/Emacs!")
(setq dashboard-items '((recents  . 2)
                        (bookmarks . 2)
                        (projects . 2)
;;                        (agenda . 5)
                        (registers . 5)))
#+end_src
** Which-key
El which-key te enseña las combinaciones de teclas posibles al pulsar alguna.
#+begin_src emacs-lisp
(which-key-mode 1)
#+end_src
** Winner-mode
El winner-mode sirve para poder hacer y deshacer la configuración de ventanas.
#+begin_src emacs-lisp
    ;; Con C-c <flechas> se hace o deshace la config de ventanas
    (winner-mode 1)
#+end_src
** Ajustes visuales y miscelánea
Pequeños ajustes visuales, creación de carpeta backup para guardar los archivos de recuperación que crea emacs, e inicio del servidor para poder acceder a emacs de forma rápida con emacsclient.
#+begin_src emacs-lisp
  ;; Poner los backups en la carpeta backup 
  (setq backup-directory-alist '(("." . "~/.emacs.d/backup")))
  (column-number-mode 1)
  (add-hook 'prog-mode-hook 'display-line-numbers-mode)
  (global-visual-line-mode)
  (add-hook 'text-mode-hook #'turn-on-auto-fill)
  (menu-bar-mode -1)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)

  (load-theme 'modus-vivendi t)

  (setq inhibit-splash-screen t)
  (server-start)
  ;; (if 'server-running-p nil
  ;;   (progn
  ;;     (server-start)
  ;;     (message "Servidor iniciado")
  ;;     )
  ;;   )
  (setq confirm-kill-emacs 'y-or-n-p)

#+end_src
** Revert-mode
Para poder sincronizar sin problema mis archivos con el cliente de Nextcloud que tengo, habilito el revert mode de forma automática para que se actualicen los búferes solos.
#+BEGIN_SRC emacs-lisp

(global-auto-revert-mode 1)

#+END_SRC
** Paréntesis
Insertar el cierre de paréntesis de forma automática y resaltar los paréntesis.
#+begin_src emacs-lisp
(electric-pair-mode 1)
(show-paren-mode 1)
#+end_src
** Scratch
Modo scratch para abrir búferes borradores en diferentes modos. Función mejorada por Protesilaos:
https://protesilaos.com/codelog/2021-07-24-emacs-misc-custom-commands/
La vi usarla en el vídeo del link, pero la saqué de su config de Emacs; [[file:~/Documentos/Configs de emacs/prot-emacs.org::#h:2695bfa4-89b4-4d7f-aa6e-8ef42f9177aa][Scratch buffers per major-mode]]
#+begin_src emacs-lisp
  (defun prot/scratch-buffer-setup ()
    "Add contents to `scratch' buffer and name it accordingly.
  If region is active, add its contents to the new buffer."
    (let* ((mode major-mode)
	   (string (format "Scratch buffer for: %s\n\n" mode))
	   (region (with-current-buffer (current-buffer)
		     (if (region-active-p)
			 (buffer-substring-no-properties
			  (region-beginning)
			  (region-end)))
		     ""))
	   (text (concat string region)))
      (when scratch-buffer
	(save-excursion
	  (insert text)
	  (goto-char (point-min))
	  (comment-region (point-at-bol) (point-at-eol)))
	(forward-line 2))
      (rename-buffer (format "*Scratch for %s*" mode) t)))
  (add-hook 'scratch-create-buffer-hook #'prot/scratch-buffer-setup)
  (define-key global-map (kbd "C-c s") #'scratch)
  (define-key global-map (kbd "C-c S") #'scratch-buffer)
#+end_src
Con el prefijo C-u se puede elegir el modo del búfer en scratch.
** Hora
#+begin_src emacs-lisp
(display-time-mode 1)
(setq display-time-24hr-format t)
#+end_src
** Smart mode line y mode line
*** Smart mode line
Con smart mode line se trunca la mode line de forma automática, lo que
me permite tener una mode line mejor para cuando uso Telega en un
frame de tamaño reducido. Ahora mismo lo tengo desactivado porque no
he ocnseguido compilar TDlib con la versión correcta para que me
funcione Telega.
#+begin_src emacs-lisp :tangle no
(sml/setup)
#+end_src
*** Mode line
Configuración de las cosas mostradas en la barra de Emacs.
#+begin_src emacs-lisp
(display-battery-mode 1)
#+end_src
** Recentf
  Con recentf-mode se puede acceder fácilmente a los ficheros usados más recientemente, y también a los [[*Entorno del editor][búferes]]
  #+begin_src emacs-lisp
    (recentf-mode 1)
  #+end_src
** Guardado
Guarda el estado de un búfer cuando se cierra éste o Emacs.
#+BEGIN_SRC emacs-lisp
(save-place-mode 1)
#+END_SRC
** LIN
Paquete de Prot para darle énfasis al hl-line-mode.
#+begin_src emacs-lisp
  (require 'lin)
  (setq lin-mode-hooks
	'(bongo-mode-hook
	  dired-mode-hook
	  elfeed-search-mode-hook
	  git-rebase-mode-hook
	  grep-mode-hook
	  ibuffer-mode-hook
	  ilist-mode-hook
	  ledger-report-mode-hook
	  log-view-mode-hook
	  emms-playlist-mode-hook
	  magit-log-mode-hook
	  mu4e-headers-mode
	  notmuch-search-mode-hook
	  notmuch-tree-mode-hook
	  occur-mode-hook
	  org-agenda-mode-hook
	  pdf-outline-buffer-mode-hook
	  proced-mode-hook
	  tabulated-list-mode-hook))

  (lin-global-mode 1)
#+end_src
** Puesta de sol
Pongo aquí una función que me permite leer las coordenadas en las que me encuentro para poder ver la puesta de sol con (sunrise-sunset).
#+BEGIN_SRC emacs-lisp

    ;;Puesta de sol
    (defun eval-file (file)
      "Execute FILE and return the result of the last expression."
      (eval
       (ignore-errors
	 (read-from-whole-string
	  (with-temp-buffer
	    (insert-file-contents file)
	    (buffer-string))))))

    (setq calendar-latitude (eval-file "~/Plantillas/lat.el"))
    (setq calendar-longitude (eval-file "~/Plantillas/lon.el"))
#+END_SRC
* Motores de completado
Paquetes que forman la interfaz de búsqueda y completado. Con company se autocompletan palabras. Ido es una interfaz muy básica para completar búsquedas entre búferes o archivos y Helm es un framework de búsqueda.
** Company
Con company se autocompletan palabras.
  #+begin_src emacs-lisp
    (global-company-mode 1)
    (with-eval-after-load 'company
      (add-to-list 'company-backends 'hledger-company)
      (add-to-list 'company-backends 'company-ebdb))
    (add-hook 'after-init-hook 'global-company-mode)
    (setq company-idle-delay 0.3)
    (setq company-show-numbers t)
    (setq company-minimum-prefix-length 2)
    (setq company-tooltip-align-annotations t)
#+end_src
** Ido
Sistema de autocompletado, ahora mismo uso otro distinto.
#+begin_src emacs-lisp :tangle no
    ;; https://www.masteringemacs.org/article/introduction-to-ido-mode
   (ido-mode)
   (setq ido-everywhere t)
   (setq ido-enable-flex-matching t)
   (setq ido-use-virtual-buffers t)
#+end_src

** Helm
  Dado que ido parece que no funciona en todas partes (por ejemplo al cambiar de nodo en org-roam), voy a probar con helm a ver cómo me va. Para empezar sólo voy a poner la configuración mínima, mi idea es coger el código de http://tuhdo.github.io/helm-intro.html ya que es la configuración que usaba cuando tenía Prelude instalado.

EDIT: Ahora mismo uso Vertico en vez de Helm, así que lo desactivo.  
  #+begin_src emacs-lisp :tangle no
    (require 'helm)
    (helm-mode 1)
    (global-set-key (kbd "M-x") 'helm-M-x)
    (global-set-key (kbd "C-x C-f") 'helm-find-files)
    (global-set-key (kbd "C-x b") 'helm-buffers-list)
  #+end_src

** Vertico, Orderless, Marginalia y Embark
Parece que es lo más popular últimamente. Voy a probarlo ya que los modus-themes no funcionan con Helm. Orderless para filtrar las búsquedas suele ir siempre en combinación con Vertico. También se suele acompañar de Marginalia para descripciones. Con embark (y embark-consult) ya forman el wombo combo.

Edit: De momento me gusta la combinación, la voy a mantener por ahora.
#+begin_src emacs-lisp
  (vertico-mode 1)
  (require 'orderless)
  (setq completion-styles '(orderless basic)
	completion-category-overrides '((file (styles basic partial-completion))))
  (marginalia-mode 1)
  (define-key global-map (kbd "C-.") #'embark-act)
  (define-key global-map (kbd "C-,") #'embark-dwim)
  (define-key global-map (kbd "C-h B") #'embark-bindings)
  (setq prefix-help-command #'embark-prefix-help-command)
  (add-hook 'eldoc-documentation-functions #'embark-eldoc-first-target)
  (add-to-list 'display-buffer-alist
		 '("\\`\\*Embark Collect \\(Live\\|Completions\\)\\*"
		   nil
		   (window-parameters (mode-line-format . none))))
#+end_src
* Eshell
La eshell es una shell escrita entera en lisp.
#+begin_src emacs-lisp
  ;; Para usar sudo bien en eshell (alias actualizar)
  (require 'em-tramp)
  (require 'em-hist)
  ;; Para poder usar el path de BASH en la eshell
  (when (memq window-system '(mac ns x))
    (exec-path-from-shell-initialize))
  ;; Guardar sesión de las shells
  (savehist-mode 1)
  (defun sudeame ()
  "Use TRAMP to `sudo' the current buffer"
  (interactive)
  (when buffer-file-name
  (find-alternate-file
  (concat "/sudo:root@localhost:"
	  buffer-file-name))))

  (setq eshell-history-size 2000)

  ;;Función de Protesilaos para buscar en el historial
  (defun prot-eshell-complete-history ()
    "Insert element from Eshell history using completion."
    (interactive)
    (let ((hist (ring-elements eshell-history-ring)))
      (insert
       (completing-read "Input from history: " hist nil t))))
  (if (equal system-name "hpdeluisito")
      (message "No protcompletes")
    (define-key eshell-hist-mode-map (kbd "M-r") #'prot-eshell-complete-history)
    )
  ;;Para no guardar cosas con espacio al principio en el historial
  (setq eshell-input-filter 'eshell-input-filter-initial-space)
  ;;Autocompletado como en BASH
  (define-key eshell-mode-map (kbd "<tab>") 'company-complete)
#+end_src
* Tramp
Tramp sirve para acceder de forma remota a archivos a través de emacs con ssh, sftp, etc.
#+begin_src emacs-lisp :tangle no
  ;;ssh
  ;;Configuración por defecto para acceder a la raspi con "/-::"
  ;;a través de TRAMP
  (custom-set-variables
	     '(tramp-default-method "ssh")
	     '(tramp-default-user "pi")
	     '(tramp-default-host "192.168.1.125"))

#+end_src
* Dired
El navegador de archivos de emacs.
#+begin_src emacs-lisp

  (setq dired-listing-switches "-alh")
  (setq dired-isearch-filenames t) ;;Buscar en dired solo en los nombres.
  (setq dired-auto-revert-buffer #'dired-directory-changed-p) ; also see `dired-do-revert-buffer'
  (add-hook 'dired-mode-hook #'hl-line-mode)
  (add-hook 'dired-mode-hook #'dired-hide-details-mode)
;;  (define-key dired-mode-map (kbd "DEL") 'dired-up-directory)
  (setq dired-dwim-target t) ;; Para copiar archivos entre dos búferes de dired abiertos en la misma ventana
#+end_src
* Org
** Introducción
El modo org sirve para organizarte la vida. En principio sólo es un lenguaje de marcado tipo Markdown, usando asteriscos como niveles jerárquicos de organización para poder contraerlos y así tener los archivos ordenados.

Para navegar por los enlaces de un archivo de org se puede usar =C-c C-o=, en vez de pulsar intro. Alternativamente se puede pinchar con el ratón en el enlace.

Para evaluar un bloque de código mientras estás en un archivo org, se puede usar la estructura siguiente, por ejemplo para Bash:

#+begin_src sh
ls
#+end_src

Y ejecutar C-c C-c dentro del bloque. Pero antes de hacerlo hay que cargar el módulo de org-babel para Bash.
** Org-babel
#+begin_src emacs-lisp
  (org-babel-do-load-languages 'org-babel-load-languages
      '(
	  (shell . t)
	  (octave . t)
      )
  )
#+end_src
Fuente: https://stackoverflow.com/questions/29163164/how-can-i-load-bash-as-opposed-to-sh-in-org-babel-to-enable-begin-src-bash
** Asignaciones de teclas
Asignaciones de teclas sugeridas por el manual de org de info.
#+BEGIN_SRC emacs-lisp

     (global-set-key "\C-cl" 'org-store-link)
     (global-set-key "\C-ca" 'org-agenda)
     (global-set-key "\C-cc" 'org-capture)
     (global-set-key "\C-cb" 'org-switchb)
#+END_SRC
Con la siguiente asignación se crea un menú parecido a imenu al pulsar C-c C-j en un org búfer para moverse bien por él. También habilito org-speed-commands, una forma de moverse rápidamente por encabezados de org con las siguientes teclas (siempre que estemos en un encabezado (es decir, con el cursor situado en un asterisco)):

n : moverse al siguiente encabezado visible
p : moverse al anterior encabezado visible
f : moverse al siguiente encabezado del mismo nivel
p : moverse al anterior encabezado del mismo nivel
c : ciclo de org
C : hace lo mismo que shifttab

Para ver el resto de asignaciones de teclas, pulsar =C-h o org-speed-commands=
#+begin_src emacs-lisp
  (setq org-goto-interface 'outline-path-completion)
  (setq org-use-speed-commands t)
#+end_src
** Plantillas y refile
Setup del refile patrocinado por: https://sachachua.com/blog/2015/02/learn-take-notes-efficiently-org-mode/. Aquí defino las plantillas para org. Si tomo una nota que no cuadra con ninguna categoría uso el template de "Nota" y luego hago el refill (C-w).
#+BEGIN_SRC  emacs-lisp

  (setq org-refile-targets  '((org-agenda-files :maxlevel . 6)
			      ("~/org-roam/20210909170753-proyectos_futuros.org" :maxlevel . 6)
			      ("~/org-roam/20210920115613-lista_de_libros.org" :maxlevel . 6)
			      ("~/org-roam/20210920111342-lista_de_juegos.org" :maxlevel . 6)
			      ("~/org-roam/20210920115726-lista_de_peliculas.org" :maxlevel . 6)
			      ("~/org-roam/20210910223458-shell.org" :maxlevel . 6)
			      ("~/org-roam/20210930132055-lista_de_series.org" :maxlevel . 6)
			      ("~/org-roam/20210930211941-notas_generales.org" :maxlevel . 6)
			      ("~/org-roam/20220210155738-metodos.org" :maxlevel . 6)
			      ("~/org-roam/20210930135146-inbox.org" :maxlevel . 6)))

      (global-set-key "\C-cc" 'org-capture)
  (when (file-exists-p "~/org")
    (setq org-capture-templates
	    (quote
	     (("c" "Nota" entry
	       (file+datetree "~/Nextcloud/notas.org")
	       "* %?" :empty-lines 1)
	      ("t" "Todo" entry
	       (file+headline "~/org/gtd.org" "Tasks")
	       "* TODO %?" :empty-lines 1)
	      ("j" "Journal Entry" entry
	       (file+datetree "~/Nextcloud/journal/journal.org.gpg")
	       "* %<%H:%M>\n %?" :empty-lines 1 :time-prompt t)
	      ("k" "Cita" entry
	       (file+headline "~/org/uni.org" "Citas")
	       "* %^t %?")
	      ))))
      (setq org-agenda-span 'day)
	;;calendario

	(setq calendar-week-start-day 1)

#+END_SRC
Plantillas para introducir código con expansión de cosas como <el con TAB.
#+begin_src emacs-lisp
(require 'org-tempo)
(add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
#+end_src
** Módulos de Org
En esta sección configuro pequeños "módulos" de Org.
*** Org-bullets
Sustitución de los asteriscos por marcas más visuales.
#+begin_src emacs-lisp
(require 'org-bullets)
(add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
#+end_src
*** Org-roam
Org-roam es una herramienta para crear un sistema de gestión personal basado en Zettelkasten. Trata de reproducir Roam Research’s, una web que sirve para implementar Zettelkasten.
   #+begin_src emacs-lisp
		 (setq org-roam-v2-ack t)
	    (when (file-exists-p "~/org-roam")
		 (setq org-roam-directory "~/org-roam"))
		 (global-set-key "\C-cnl" 'org-roam-buffer-toggle)
		 (global-set-key "\C-cnf" 'org-roam-node-find)
		 (global-set-key "\C-cng" 'org-roam-graph)
		 (global-set-key "\C-cni" 'org-roam-node-insert)
		 (global-set-key "\C-cnc" 'org-roam-capture)
		 ;; Dailies
		 (global-set-key "\C-cnj" 'org-roam-dailies-capture-today)
	    (when (file-exists-p "~/org-roam")
	      (org-roam-db-autosync-mode)
	      	    (org-roam-setup))

   #+end_src
*** Org-static-blog
   Publicación de entradas en un blog
   #+begin_src emacs-lisp
     (setq org-static-blog-publish-title "Libre como en libertad")
     (setq org-static-blog-publish-url "http://www.finaprosadigital.com/publish/blog")
     (setq org-static-blog-publish-directory "~/blog/")
     (setq org-static-blog-posts-directory "~/blog/posts")
     (setq org-static-blog-drafts-directory "~/blog/drafts")
     (setq org-static-blog-enable-tags t)
     (setq org-export-with-toc nil)
     (setq org-export-with-section-numbers nil)


     (setq org-static-blog-page-header
     "<meta name=\"author\" content=\"Carlos Pajuelo\">
     <meta name=\"referrer\" content=\"no-referrer\">
     <link href= \"static/style.css\" rel=\"stylesheet\" type=\"text/css\" />
     <link rel=\"icon\" href=\"static/arroba.ico\">
     <link rel=\"apple-touch-icon-precomposed\" href=\"static/arroba.png\">
     <link rel=\"msapplication-TitleImage\" href=\"static/arroba.png\">
     <link rel=\"msapplication-TitleColor\" href=\"#0141ff\">
     <script src=\"static/katex.min.js\"></script>
     <script src=\"static/auto-render.min.js\"></script>
     <link rel=\"stylesheet\" href=\"static/katex.min.css\">
     <script>document.addEventListener(\"DOMContentLoaded\", function() { renderMathInElement(document.body); });</script>
     <meta http-equiv=\"content-type\" content=\"application/xhtml+xml; charset=UTF-8\">
     <meta name=\"viewport\" content=\"initial-scale=1,width=device-width,minimum-scale=1\">")

     (setq org-static-blog-page-preamble
     "<div class=\"header\">
       <a href=\"http://www.finaprosadigital.com/publish/blog\">Blog sobre software libre</a>
       <div class=\"sitelinks\">
	 <a href=\"https://gitlab.com/gnuhack\">Gitlab</a> | <a href=\"https://github.com/gnuhack\">Github</a> | <a href=\"http://finaprosadigital.com/publish/blog/rss.xml\">RSS</a>
       </div>
     </div>")

     (setq org-static-blog-page-postamble
     "<div id=\"archive\">
       <a href=\"http://www.finaprosadigital.com/publish/blog/archive.html\">Other posts</a>
     </div>

     <center><a rel=\"license\" href=\"https://creativecommons.org/licenses/by-sa/3.0/\"><img alt=\"Creative Commons License\" style=\"border-width:0\" src=\"https://i.creativecommons.org/l/by-sa/3.0/88x31.png\" /></a><br /><span xmlns:dct=\"https://purl.org/dc/terms/\" href=\"https://purl.org/dc/dcmitype/Text\" property=\"dct:title\" rel=\"dct:type\">www.finaprosadigital.com</span> by <a xmlns:cc=\"https://creativecommons.org/ns#\" href=\"http://www.finaprosadigital.com\" property=\"cc:attributionName\" rel=\"cc:attributionURL\">Carlos Pajuelo</a> is licensed under a <a rel=\"license\" href=\"https://creativecommons.org/licenses/by-sa/3.0/\">Creative Commons Attribution-ShareAlike 3.0 Unported License</a>.</center>")

   #+end_src
*** Org-pomodoro
   Ténica de trabajo con descansos cortos. https://github.com/marcinkoziej/org-pomodoro
   #+begin_src emacs-lisp
     ;; Sonido de https://freesound.org/people/.Andre_Onate/sounds/484665/
     (setq org-clock-sound "~/Descargas/ding.wav")
     ;; Para iniciar el crono, pulsar C-c C-x ;
     (setq org-timer-default-timer "00:25:00")
   #+end_src
*** Org-agenda
   Vacaciones del curso 2021-2022
   #+begin_src emacs-lisp
	  (setq holiday-other-holidays '((holiday-fixed 10 12 "Día de mi Españita")
					 (holiday-fixed 12 23 "Navidad")
					 (holiday-fixed 12 24 "Navidad")
					 (holiday-fixed 11 01 "Día de todos los santos")
					 (holiday-fixed 12 06 "Día de la Constitución")
					 (holiday-fixed 12 08 "Festividad de la Imnaculada")
					 (holiday-fixed 01 28 "Santo Tomás de Aquino (Aquí no, aquí no...)")
					 (holiday-fixed 02 28 "Día del Glorious Anthem of Andalusia")
					 (holiday-fixed 05 02 "Día del trabajo")
					 (holiday-fixed 05 04 "Fiesta local")
					 (holiday-fixed 06 16 "Corpus Christi")))

     (setq holiday-general-holidays nil)
     (setq holiday-local-holidays nil)
     (setq holiday-solar-holidays nil)
     (setq holiday-bahai-holidays nil)
     (setq holiday-christian-holidays nil)
     (setq holiday-hebrew-holidays nil)
     (setq holiday-islamic-holidays nil)
     (setq holiday-oriental-holidays nil)
   #+end_src
*** Org-habit
   Para hábitos a los que les quiera hacer un seguimiento se puede usar [[info:org#Tracking your habits][org-habit]]
   #+begin_src emacs-lisp :tangle no
	﻿(require 'org-habit)
   #+end_src
*** Org-books
Para gestionar los libros que me he leído voy a probar a usar org-books.
#+begin_src emacs-lisp
  (setq org-books-file "~/org-roam/20210920115613-lista_de_libros.org")
  (setq org-books-add-to-top nil)
  (setq org-books-file-depth 3) ;; Reconocer los subheadings hasta de tercer nivel como categorías.
#+end_src
Como mi archivo de libros he puesto el mismo que tengo en org-roam, porque creo que se pueden complementar bien org-roam con org-books.

Para añadir un libro que me he leído solo tengo que usar =org-books-add-book= y poner el título y el heading en el que lo quiero meter.
*** Org-timestamps
Para que cuando se cierre un TODO se ponga automáticamente la fecha se pone la variable =org-log-done= a time
#+begin_src emacs-lisp
  (setq org-log-done 'time)
#+end_src 
*** Org-alert
Para avisar de las citas de la agenda
#+begin_src emacs-lisp :tangle no
  (org-alert-enable)
#+end_src
* Notificaciones
Funciones para que las notificaciones de la agenda me lleguen al escritorio con espeak. Además del código de abajo hace falta meter en ~/bin un appt-notification con lo siguiente (además de instalar espeak):
#+BEGIN_SRC 
#!/bin/sh

TIME="$1"
MSG="$2"

notify-send -t 0 "Appointment in $TIME minutes:$MSG"
espeak "Appointment in $TIME minutes: $MSG"

#+END_SRC
Aquí están las funciones para la notificación.
#+BEGIN_SRC emacs-lisp
  (require 'appt)
  (appt-activate t)

  (setq appt-message-warning-time 30) ; Show notification 30 minutes before event
  (setq appt-display-interval appt-message-warning-time) ; Disable multiple reminders
  (setq appt-display-mode-line nil)

  ; Use appointment data from org-mode
  (defun my-org-agenda-to-appt ()
    (interactive)
    (setq appt-time-msg-list nil)
    (org-agenda-to-appt))

  ; Update alarms when...
  ; (1) ... Starting Emacs
  (when (file-exists-p "~/org")
    (my-org-agenda-to-appt))

  ; (2) ... Everyday at 12:05am (useful in case you keep Emacs always on)
  (when (file-exists-p "~/org")
    (run-at-time "12:05am" (* 24 3600) 'my-org-agenda-to-appt))

  ; (3) ... When TODO.txt is saved
  (when (file-exists-p "~/org")
    (add-hook 'after-save-hook
	    '(lambda ()
	       (if (string= (buffer-file-name) (concat (getenv "HOME") "/org/uni.org"))
		   (my-org-agenda-to-appt)))))

  ; Display appointments as a window manager notification
  (setq appt-disp-window-function 'my-appt-display)
  (setq appt-delete-window-function (lambda () t))

  (setq my-appt-notification-app (concat (getenv "HOME") "/bin/appt-notification"))

  (defun my-appt-display (min-to-app new-time msg)
    (if (atom min-to-app)
      (start-process "my-appt-notification-app" nil my-appt-notification-app min-to-app msg)
    (dolist (i (number-sequence 0 (1- (length min-to-app))))
      (start-process "my-appt-notification-app" nil my-appt-notification-app (nth i min-to-app) (nth i msg)))))
#+END_SRC
* PDF
Macro para poner el modo noche en los pdfs (modonoche) y funciones para conseguir un marcapáginas en un pdf. Sacado de https://sachachua.com/blog/2021/02/guest-post-bookmarking-pdfs-in-emacs-with-pdf-tools-and-registers/
#+BEGIN_SRC emacs-lisp

  (fset 'modonoche
	(lambda (&optional arg) "Keyboard macro." (interactive "p") (kmacro-exec-ring-item (quote ("m" 0 "%d")) arg)))
  (add-hook 'pdf-view-mode-hook (lambda() (nlinum-mode -1))) ;;Desactivar linum mode, que no va bien con pdf-view-mode
  (pdf-tools-install)

  (define-key pdf-view-mode-map (kbd "<C-f2>")
    (lambda ()
      "Loads the position saved by <C-f1>."
      (interactive)
	(if (y-or-n-p "¿Seguro que quieres cargar la posición?")
	    (pdf-view-bookmark-jump my-bookmark))
  ))

  (define-key pdf-view-mode-map (kbd "<C-f1>")
    (lambda ()
      "Saves the current position on the pdf to jump to later with <C-f2>."
      (interactive)
      (if (y-or-n-p "¿Seguro que quieres guardar la posición?")
	  (setf my-bookmark (pdf-view-bookmark-make-record))
	(message "Posición no guardada"))
  ))
#+END_SRC
* Elfeed
Con elfeed puedo tener mi propio feed personalizado. Sobre todo es útil para seguir blogs individuales que no tengan una alta frecuencia de posteo. También me sirve para "suscribirme" a canales de Youtube sin visitar la página, gracias as la función definida abajo. He quitado la parte de =emacs-lisp= al lado de #+BEGIN_SRC para que no se evalúe este código, ya que ahora se encarga de elfeed el fichero init.el.
#+BEGIN_SRC  emacs-lisp :tangle no
  (define-key elfeed-search-mode-map (kbd "SPC") #'scroll-up-command)
  (define-key elfeed-search-mode-map (kbd "DEL") #'scroll-down-command)
#+END_SRC
Con la siguiente función puedo reproducir vídeos de Youtube en mpv descargándolos con youtube-dl. Solo hay que ponerse sobre el link de Youtube y hacer =M-x std::elfeed::visit-entry-dwim=
#+BEGIN_SRC emacs-lisp

(defun std::elfeed::visit-entry-dwim (&optional arg)
  "Función para reproducir vídeos en elfeed de Youtube con mpv ARG."
  (interactive "P")
  (if arg
      (elfeed-search-browse-url)
    (-let [entry (if (eq major-mode 'elfeed-show-mode) elfeed-show-entry (elfeed-search-selected :single))]
      (if (s-matches? (rx "https://www.youtube.com/watch" (1+ any))
                      (elfeed-entry-link entry))
          (let* ((quality (completing-read "Max height resolution (0 for unlimited): " '("0" "480" "720" "1080")))
                 (format (if (= 0 (string-to-number quality)) "" (format "--ytdl-format=[height<=?%s]" quality))))
            (message "Opening %s with height ≤ %s with mpv..."
                     (elfeed-entry-link entry) quality)
            (elfeed-untag entry 'unread)
            (start-process "elfeed-mpv" nil "mpv" format (elfeed-entry-link entry))
            (elfeed-search-update :force))
        (if (eq major-mode 'elfeed-search-mode)
            (elfeed-search-browse-url)
          (elfeed-show-visit))))))
#+END_SRC
Para ver los enlaces de Elfeed con Firefox (por defecto los veo con eww):
#+begin_src emacs-lisp
  (defun elfeed-firefox-open (&optional use-generic-p)
    "open with firefox"
    (interactive "P")
    (let ((entries (elfeed-search-selected)))
      (cl-loop for entry in entries
	       do (elfeed-untag entry 'unread)
	       when (elfeed-entry-link entry)
	       do (browse-url-firefox it))
      (mapc #'elfeed-search-update-entry entries)
      (unless (use-region-p) (forward-line))))

;;  (define-key elfeed-search-mode-map (kbd "f") 'elfeed-firefox-open)
#+end_src
* EMMS
Para reproducir música he elegido emms, que es bastante simple de configurar. Para que se carguen los datos en caché la primera vez que use emms hay que añadir a la lista de reproducción la carpeta de música que quiera reproducir (con add-directory-tree) y luego ya iniciarlo con emms-start.

También he descubierto cómo guardar y cargar playlist. Simplemente cuando tengo una playlist (por ejemplo me puedo construir una desde cero gracias a =emms-smart-browse=) la puedo guardar con =C-x C-s= como si fuera un búfer normal, y luego si la quiero cargar (por ejemplo al abrir Emacs) puedo usar =emms-add-playlist=.
#+BEGIN_SRC emacs-lisp
  ;;emms
  (require 'emms-setup)
  (emms-all)
  (emms-default-players)
  (setq emms-source-file-default-directory "~/Música/")
  (emms-add-playlist "~/Música/Todomenosmeyest")
  (emms-shuffle)
  (emms-playing-time-mode 0)
  (require 'emms-history)
  ;;(emms-history-load)
  (emms-mode-line-disable)
  (emms-playing-time-mode-line)
  (global-set-key (kbd "<XF86AudioPrev>") 'emms-previous)
  (global-set-key (kbd "<XF86AudioNext>") 'emms-next)
  (global-set-key (kbd "<XF86AudioPlay>") 'emms-pause)
  (global-set-key (kbd "<XF86MonBrightnessUp>") 'emms-shuffle) 
  (add-hook 'emms-mode-hook 'hl-line-mode)
  (add-hook 'emms-mode-hook 'visual-line-mode)
  (global-set-key (kbd "s-i") 'emms)
#+END_SRC
* Keybindings
Atajos de teclas y registros. https://www.masteringemacs.org/article/mastering-key-bindings-emacs
#+BEGIN_SRC emacs-lisp
    (global-set-key (kbd "s-<return>") 'vterm)
    (global-set-key (kbd "C-x w") 'elfeed)
    (global-set-key (kbd "C-<tab>") 'hippie-expand)
  ;;(global-set-key (kbd "C-<iso-lefttab>") 'previous-buffer)
  ;;(global-set-key (kbd "C-x p") 'proced)
    (global-set-key (kbd "C-x e") 'eshell)
    (global-set-key (kbd "C-c y") 'clipboard-yank)
    (global-set-key (kbd "C-x t") 'shell)
    (global-set-key (kbd "C-c m") 'calendar)
    (global-set-key (kbd "M-o") 'other-window)
    (global-set-key (kbd "s-o") 'other-window)
    (global-set-key (kbd "C-x k") 'kill-current-buffer)
    (global-set-key (kbd "<f5>") 'modonoche)
    (add-to-list 'org-file-apps '("pdf" . "evince %s"))
    (global-set-key (kbd "<f6>") 'quick-calc)
    (set-register ?E (cons 'file "~/Documentos/ETSI/ETSI 2024"))
    (set-register ?o (cons 'file "~/Nextcloud/Documents/horario.txt"))
    (set-register ?e (cons 'file "~/git/dotfiles/.emacs.d/emacs-literario.org"))
    (set-register ?t (cons 'file "~/org/2021t/tiempo.org"))
    (set-register ?c (cons 'file "~/.config/i3/config"))
    (set-register ?d (cons 'file "~/Descargas"))
    (global-set-key (kbd "s-n") 'next-buffer)
    (global-set-key (kbd "s-p") 'previous-buffer)
    ;;(global-set-key (kbd "s-<backspace>") 'rat/killydelete)
    ;;(global-set-key (kbd "s-<return>") 'rat/terminal)
    (define-key dired-mode-map (kbd "<tab>") #'dired-subtree-toggle)
    (define-key dired-mode-map (kbd "<C-tab>") #'dired-subtree-cycle)
    (define-key dired-mode-map (kbd "<backtab>") #'dired-subtree-remove)
#+END_SRC
* Project
Para gestionar proyectos uso project.el, integrado en Emacs. Así puedo cambiar entre archivos de un proyecto de forma fácil y cómoda. Un proyecto es toda carpeta que contenga archivos clave (como los repos de git).

* Telega
Cliente de Telegram para Emacs. Ahora mismo no me funciona porque no
sé compilar TDlib.
#+BEGIN_SRC emacs-lisp
  (setq emojify-emoji-styles '(unicode))
  (global-set-key (kbd "s-T") 'telega)
  (define-key global-map (kbd "C-c t") telega-prefix-map)
  (add-hook 'telega-load-hook 'telega-notifications-mode)
  (setq telega-chat-fill-column 70)
  ;;(add-hook 'telega-load-hook 'emoji-mode)
  (add-hook 'after-init-hook #'global-emojify-mode)
  (add-hook 'telega-chat-mode-hook 'variable-pitch-mode)
  (add-hook 'telega-root-mode-hook 'hl-line-mode)
  (add-hook 'telega-chat-mode-hook 'company-mode) ;; No consigo desactivar company al entrar a chats por defecto
  (add-hook 'telega-chat-mode-hook 'abbrev-mode)
  ;; Notificaciones
  (telega-appindicator-mode 1)
  (telega-mode-line-mode 1)
#+END_SRC
* Correo
Configuración copiada de mi antiguo .emacs.el de cuando usaba Prelude
y GNUS. Para los contactos uso
EBDB. (https://chrisdone.com/posts/emacs-mail/). Pendiente de configurar.
#+begin_src emacs-lisp
  (require 'ebdb-message) ;;Cargar la ebdb con los contactos
  (global-set-key (kbd "s-m") 'notmuch-hello)
  ;;   (setq send-mail-function 'smtpmail-send-it)
  ;;   (setq smtpmail-smtp-user   "nkolita1")
  ;;   (setq smtpmail-smtp-server "smtp.gmail.com")
  ;;   (setq smtpmail-smtp-service 587)
  (setq gnus-select-method
	'(nnmaildir "GMail"
		    (directory "~/Test")
		    (directory-files nnheader-directory-files-safe)
		    (get-new-mail nil)))

  ;;   (setq message-send-mail-function   'smtpmail-send-it
  ;;	 smtpmail-default-smtp-server "smtp.gmail.com"
  ;;	 smtpmail-smtp-server         "smtp.gmail.com"
  ;;	 smtpmail-local-domain        "mail.google.com")

  ;; Por fin he conseguido enviar correos con hotmail

  ;; (setq message-send-mail-function 'smtpmail-send-it
  ;; 	   smtpmail-stream-type 'starttls
  ;; 	   smtpmail-default-smtp-server "smtp.office365.com"
  ;; 	   smtpmail-smtp-server "smtp.office365.com"
  ;; 	   smtpmail-smtp-service 587
  ;; 	   smtpmail-smtp-user "carlospajuelo_@hotmail.com"
  ;; 	   ;; account info
  ;; 	   user-mail-address "carlospajuelo_@hotmail.com"
  ;; 	   user-full-name  "Carlos Pajuelo")

  ;; Y con mi cuenta personal también!!

  (setq message-send-mail-function 'smtpmail-send-it
	smtpmail-stream-type 'starttls
	smtpmail-default-smtp-server "smtp.pajuelo.com"
	smtpmail-smtp-server "smtp.pajuelo.com"
	smtpmail-smtp-service 587
	smtpmail-smtp-user "carlos@pajuelo.com"
	smtpmail-servers-requiring-authorization "smtp.pajuelo.com"
	;; account info
	user-mail-address "carlos@pajuelo.com"
	user-full-name  "Carlos")

  (defun offlineimap ()
    "Función para ejecutar offlineimap y descargar el correo en gnus."
    (interactive)
    (shell-command "offlineimap&" "*offlineimap*" nil)
    )
  (async-shell-command "offlineimap")
  (notmuch-indicator-mode)
#+end_src
Notificaciones para la modeline con notmuch-indicator
#+begin_src emacs-lisp :tangle no
  (defun notmuch-open-emails ()
    "Abre la bandeja de entrada de notmuch directamente"
    (interactive)
    (notmuch-search "tag:inbox")
    )

  (notmuch-indicator-mode)
#+end_src
* Diccionario
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-c d") #'dictionary-search)
(setq dictionary-server "dict.org")

#+END_SRC

* Ledger
  [[file:~/org-roam/20220204152645-ledger.org::+title: Ledger][Ledger]] es una herramienta para llevar la contabilidad. Hledger es el port a Haskell de Ledger. Setup básico de la página oficial https://github.com/narendraj9/hledger-mode
  #+begin_src emacs-lisp
     ;;; Basic configuration
     (require 'hledger-mode)

     ;; To open files with .dat extension in hledger-mode
     (add-to-list 'auto-mode-alist '("\\.dat\\'" . hledger-mode))

     ;; Provide the path to you journal file.
     ;; The default location is too opinionated.
     (setq hledger-jfile "~/Documentos/cuentas.dat")
     (setq hledger-currency-string "€")


     ;;; Auto-completion for account names
     ;; For company-mode users,
    ;;(add-to-list 'company-backends 'hledger-company)
    ;; Keybindings
    (global-set-key (kbd "C-c e") 'hledger-jentry)
    (global-set-key (kbd "C-c j") 'hledger-run-command)
    (add-hook 'hledger-jentry-hook 'hledger-time )
  #+end_src

* Engine mode 
  Con el engine-mode se puede usar Emacs como interfaz de motores de búsqueda en la web.
  #+begin_src emacs-lisp
    (engine-mode 1)
    (setq engine/browser-function 'eww-browse-url)
    (engine/set-keymap-prefix (kbd "C-c w"))

    (defengine duckduckgo
      "https://duckduckgo.com/?q=%s"
      :keybinding "d")
    (defengine rae
      "https://dle.rae.es/%s"
      :keybinding "D")
    (defengine wikipedia-en
      "http://www.wikipedia.org/search-redirect.php?language=en&go=Go&search=%s"
      :keybinding "w"
      :docstring "Searchin' the wikis.")
    (defengine wikipedia-es
      "http://www.wikipedia.org/search-redirect.php?language=es&go=Go&search=%s"
      :keybinding "W"
      :docstring "Searchin' the wikis.")
    (defengine searx
      "http://www.searx.be/?q=%s"
      :keybinding "s"
      :docstring "Searchin' the searx.")
    (defengine urbandictionary
      "https://www.urbandictionary.com/define.php?term=%s"
      :keybinding "u"
      :docstring "Searchin' the urbs.")
  #+end_src

* Eww
Navegador web de Emacs.
#+begin_src emacs-lisp
  (setq browse-url-browser-function 'eww) ;Para abrir los feeds de elfeed con eww en vez de firefox.
  (setq eww-auto-rename-buffer 'title) ;Para renombrar los búferes de eww automáticamente
#+end_src

* Popper
Para poder sacar una terminal de octave en cualquier momento, uso popper.
** Uso básico
Se activa con =popper-mode=. Después, cuando esté en el búfer que quiera convertir en una ventana emergente (pop-up), uso =M-x popper-toggle-type=. Y cada vez que quiera hacer aparecer o desaparecer esa ventana =popper-toggle-latest=.
#+begin_src emacs-lisp
  (global-set-key (kbd "<f9>") 'popper-toggle-latest)
#+end_src
Para poner un hook que encoja la ventana he hecho una solución provisional hasta que tenga tiempo de mirarlo.
#+begin_src emacs-lisp
(defun esrinca ()
  "Achica un frame."
  (interactive)
  (shrink-window 5))
(add-hook 'popper-open-popup-hook 'esrinca)
#+end_src

* Octave
#+begin_src emacs-lisp
  (autoload 'octave-mode "octave-mod" nil t)
  (setq auto-mode-alist
	(cons '("\\.m$" . octave-mode) auto-mode-alist))
  (define-key global-map (kbd "C-c o") #'run-octave)
  (define-key global-map (kbd "C-c O") #'helm-info-octave)
#+end_src
* ERC
Cliente para conectarse a IRC.
#+begin_src emacs-lisp
  (global-set-key "\C-cf" (lambda () (interactive)
			     (erc :server "irc.libera.chat" :port "6667"
				  :nick "gnuhack")))
  (setq erc-autojoin-channels-alist
	'(("Libera.Chat" "#emacs" "#nethack")))

  (setq erc-track-exclude-types '("JOIN" "NICK" "QUIT" "MODE" "AWAY")
	erc-hide-list '("JOIN" "NICK" "QUIT" "MODE" "AWAY")
	erc-track-exclude-server-buffer t)

  (global-set-key (kbd "C-c C-ñ") 'erc-track-switch-buffer)

#+end_src
* Sudo-save
Función para guardar archivos con sudo.
#+begin_src emacs-lisp
  (defun sudo-save ()
  (interactive)
  (if (not buffer-file-name)
      (write-file (concat "/sudo:root@localhost:" (ido-read-file-name "File:")))
    (write-file (concat "/sudo:root@localhost:" buffer-file-name))))

#+end_src
Método alternativo para editar archivos con sudo (fuente: https://chainsawriot.com/postmannheim/2022/12/11/aoe11.html).

Gracias a Helm se pueden editar archivos con sudo directamente, no hay más que buscar un archivo con helm-find-file (C-x C-f) y luego cuando esté seleccionado el archivo a editar usar C-c r para ejecutar helm-ff-run-find-file-as-root.
* C++
Configuración de Emacs como IDE de C++. Para usar las yasnippets pulsar =C-c & C-s=.
Fuente: https://linuxhint.com/c_emacs_configuration/
#+begin_src emacs-lisp
  (require 'yasnippet)
  (yas-global-mode 1)
  (ac-config-default)
  (global-auto-complete-mode t)
  ;;(global-flycheck-mode t)

  (defun code-compile ()
    (interactive)
    (unless (file-exists-p "Makefile")
      (set (make-local-variable 'compile-command)
       (let ((file (file-name-nondirectory buffer-file-name)))
	 (format "%s -o %s %s"
	     (if  (equal (file-name-extension file) "cpp") "g++" "gcc" )
	     (file-name-sans-extension file)
	     file)))
      (compile compile-command)))

  (global-set-key [f8] 'code-compile)
#+end_src

* Reloj
Reloj mundial

#+begin_src emacs-lisp
  (setq display-time-world-list
    '(("Etc/UTC" "UTC")
      ("America/Los_Angeles" "Seattle")
      ("America/New_York" "New York")
      ("Europe/Athens" "Athens")
      ("Europe/Madrid" "Madrid")))

  ;; Prueba para ver si funciona
  (define-key dired-mode-map (kbd "DEL") 'dired-up-directory)

#+end_src

* Tetris
Dentro de Emacs se puede jugar al Tetris. Pero por defecto no se usa
el método [[https://tetris.wiki/Tetris_Guideline][estándar]] para la generación aleatoria de piezas. Con esta
opción se genera una bolsa de siete piezas de tetris distintas, y
cuando se acaba la bolsa se vuelve a generar otra, para que no puedan
tocar muchas piezas repetidas.
#+begin_src lisp
(setq tetris-allow-repetitions nil)
#+end_src
