* Qué está pasando
Lo que estoy haciendo aquí es usar la programación literaria. Para ello creo que se usa "tangle" o algo así para cargar desde el archivo de inicio de emacs tradicional (el init.el) un archivo org (emacs-literario.org) que luego automágicamente se convierte en un emacs-literario.el. A partir de ahí ya se lee la configuración normal, solo que en vez de estar toda "del tirón" está en bloques (#+BEGIN_SRC emacs-lisp #+END_SRC) que son leídos y transformados adecuadamente para cargarse. Por tanto para replicar esta configuración se necesitan tener dos archivos (init.el y emacs-literario.org) y los dos en el mismo directorio (típicamente ~/.emacs.d).
***** DONE Encontrar una forma de poner los #+BEGIN_SRC emacs-lisp #+END_SRC de forma automática: Se hace con <s y luego TAB (En versiones recientes de Emacs es con C-c C-,)
***** TODO Poner las funciones de elisp en un fichero aparte
***** TODO Autoiniciar offlineimap y autoponer la contraseña
* Entorno del editor
  Para que funcione bien mi función rat/killydelete suprimo la confirmación al eliminar un búfer con un proceso.
#+begin_src emacs-lisp
    (setq kill-buffer-query-functions (delq 'process-kill-buffer-query-function kill-buffer-query-functions))
#+end_src
Para mejorar la pantalla de inicio, con dashboard se muestran archivos recientes y más cosas:
#+begin_src emacs-lisp
(dashboard-setup-startup-hook)
(setq dashboard-center-content t)
(setq dashboard-banner-logo-title "¡Bienvenido a GNU/Emacs!")
(setq dashboard-items '((recents  . 2)
                        (bookmarks . 2)
                        (projects . 2)
;;                        (agenda . 5)
                        (registers . 5)))
#+end_src
El which-key te enseña las combinaciones de teclas posibles al pulsar alguna.
#+begin_src emacs-lisp
(which-key-mode)
#+end_src
Con company se autocompletan palabras.
  #+begin_src emacs-lisp
(add-hook 'after-init-hook 'global-company-mode)
(setq company-idle-delay 0.3)
(setq company-show-numbers t)
(setq company-minimum-prefix-length 2)
(setq company-tooltip-align-annotations t)
#+end_src
Como motor de búsqueda he elegido ido, para buscar archivos fácilmente.
#+begin_src emacs-lisp
  ;; https://www.masteringemacs.org/article/introduction-to-ido-mode
  (ido-mode)
;;  (setq ido-everywhere t) ; De momento voy a probar Helm, que es incompatible con ésto.
  (setq ido-enable-flex-matching t)
  (setq ido-use-virtual-buffers t)
#+end_src
El winner-mode sirve para poder hacer y deshacer la configuración de ventanas.
#+begin_src emacs-lisp
    ;; Con C-c <flechas> se hace o deshace la config de ventanas
    (winner-mode)
#+end_src
Pequeños ajustes visuales, creación de carpeta backup para guardar los archivos de recuperación que crea emacs, e inicio del servidor para poder acceder a emacs de forma rápida con emacsclient.
#+begin_src emacs-lisp
  ;; Poner los backups en la carpeta backup 
  (setq backup-directory-alist '(("." . "~/.emacs.d/backup")))
  (column-number-mode 1)
  (add-hook 'prog-mode-hook 'display-line-numbers-mode)
  (global-visual-line-mode)

  (menu-bar-mode -1)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)
  (if (file-exists-p "~/org")
      (load-theme 'modus-vivendi t)
    (load-theme 'misterioso))

  (setq inhibit-splash-screen t)

  (server-start)
  (setq confirm-kill-emacs 'y-or-n-p)

#+end_src
Para poder sincronizar sin problema mis archivos con el cliente de Nextcloud que tengo, habilito el revert mode de forma automática para que se actualicen los búferes solos.
#+BEGIN_SRC emacs-lisp

(auto-revert-mode)

#+END_SRC
Insertar el cierre de paréntesis de forma automática
#+begin_src emacs-lisp
(electric-pair-mode)
(show-paren-mode)
#+end_src
Modo scratch para abrir búferes borradores en diferentes modos. Función mejorada por Protesilaos:
https://protesilaos.com/codelog/2021-07-24-emacs-misc-custom-commands/
La vi usarla en el vídeo del link, pero la saqué de su config de Emacs; [[file:~/Documentos/Configs de emacs/prot-emacs.org::#h:2695bfa4-89b4-4d7f-aa6e-8ef42f9177aa][Scratch buffers per major-mode]]
#+begin_src emacs-lisp
  (defun prot/scratch-buffer-setup ()
    "Add contents to `scratch' buffer and name it accordingly.
If region is active, add its contents to the new buffer."
    (let* ((mode major-mode)
           (string (format "Scratch buffer for: %s\n\n" mode))
           (region (with-current-buffer (current-buffer)
                     (if (region-active-p)
                         (buffer-substring-no-properties
                          (region-beginning)
                          (region-end)))
                     ""))
           (text (concat string region)))
      (when scratch-buffer
	    (save-excursion
          (insert text)
          (goto-char (point-min))
          (comment-region (point-at-bol) (point-at-eol)))
	    (forward-line 2))
      (rename-buffer (format "*Scratch for %s*" mode) t)))
  (add-hook 'scratch-create-buffer-hook #'prot/scratch-buffer-setup)
  (define-key global-map (kbd "C-c s") #'scratch)
#+end_src
Con el prefijo C-u se puede elegir el modo del búfer en scratch.
* Eshell
La eshell es una shell escrita entera en lisp.
#+begin_src emacs-lisp
  ;; Para usar sudo bien en eshell (alias actualizar)
  (require 'em-tramp) 
  ;; Para poder usar el path de BASH en la eshell
  (when (memq window-system '(mac ns x))
    (exec-path-from-shell-initialize))

  (defun sudeame ()
  "Use TRAMP to `sudo' the current buffer"
  (interactive)
  (when buffer-file-name
  (find-alternate-file
  (concat "/sudo:root@localhost:"
	  buffer-file-name))))
#+end_src
* Tramp
Tramp sirve para acceder de forma remota a archivos a través de emacs con ssh, sftp, etc.
#+begin_src emacs-lisp
  ;;ssh
  ;;Configuración por defecto para acceder a la raspi con "/-::"
  ;;a través de TRAMP
  ;; (custom-set-variables
  ;;            '(tramp-default-method "ssh")
  ;;            '(tramp-default-user "pi")
  ;;            '(tramp-default-host "192.168.1.125"))

#+end_src
* Dired
El navegador de archivos de emacs.
#+begin_src emacs-lisp

  (setq dired-listing-switches "-alh")
  (setq dired-isearch-filenames t) ;;Buscar en dired solo en los nombres.
  (setq dired-auto-revert-buffer #'dired-directory-changed-p) ; also see `dired-do-revert-buffer'
  (add-hook 'dired-mode-hook 'hl-line-mode)

#+end_src
* Puesta de sol
Pongo aquí una función que me permite leer las coordenadas en las que me encuentro para poder ver la puesta de sol con (sunrise-sunset).
#+BEGIN_SRC emacs-lisp
;;(global-linum-mode '0)
    ;;Puesta de sol
    (defun eval-file (file)
      "Execute FILE and return the result of the last expression."
      (eval
       (ignore-errors
	 (read-from-whole-string
	  (with-temp-buffer
	    (insert-file-contents file)
	    (buffer-string))))))

    (setq calendar-latitude (eval-file "~/Plantillas/lat.el"))
    (setq calendar-longitude (eval-file "~/Plantillas/lon.el"))
#+END_SRC
* Org
Asignaciones de teclas sugeridas por el manual de org de info.
#+BEGIN_SRC emacs-lisp

     (global-set-key "\C-cl" 'org-store-link)
     (global-set-key "\C-ca" 'org-agenda)
     (global-set-key "\C-cc" 'org-capture)
     (global-set-key "\C-cb" 'org-switchb)
#+END_SRC
Con esta asignación se crea un menú parecido a imenu al pulsar C-c C-j en un org búfer para moverse bien por él.
#+begin_src emacs-lisp
(setq org-goto-interface 'outline-path-completion)
#+end_src
Setup del refile patrocinado por: https://sachachua.com/blog/2015/02/learn-take-notes-efficiently-org-mode/. Aquí defino las plantillas para org. Si tomo una nota que no cuadra con ninguna categoría uso el template de "Nota" y luego hago el refill (C-w).
#+BEGIN_SRC  emacs-lisp

      (setq org-refile-targets '((org-agenda-files . (:maxlevel . 6))))
      (global-set-key "\C-cc" 'org-capture)
  (when (file-exists-p "~/org")
    (setq org-capture-templates
	    (quote
	     (("c" "Nota" entry
	       (file+datetree "/home/carlos/Nextcloud/Documents/horario.txt")
	       "* %?" :empty-lines 1)
	      ("t" "Todo" entry
	       (file+headline "/home/carlos/org/gtd.org" "Tasks")
	       "* TODO %?" :empty-lines 1)
	      ("j" "Journal Entry" entry
	       (file+datetree "~/Nextcloud/journal/journal.org")
	       "* %?" :empty-lines 1 :time-prompt t)
	      ("p" "Películas" entry
	       (file+headline "~/Nextcloud/Documents/horario.txt" "Películas")
	       "* %?")
	      ("d" "Dudas" entry (file+headline "/home/carlos/Nextcloud/Documents/horario.txt" "Dudas")
	       "* %^{PROMPT} %?\n  %i\n  %a")
	      ("k" "Cita" entry
	       (file+headline "~/org/uni.org" "Citas")
	       "* %^t %?")
	      ("l" "Ledger" plain
	       (file "~/Documentos/cuentas.dat")
		     "%(org-read-date) %^{Concepto}
      expenses:%^{Cuenta de gasto}  %^{Cantidad}
      assets:%^{Método de pago}  %^{Cantidad}
    ")		  
	      ))))
      (setq org-agenda-span 'day)
	;;calendario

	(setq calendar-week-start-day 1)

#+END_SRC
Plantillas para introducir código con expansión de cosas como <el con TAB.
#+begin_src emacs-lisp
(require 'org-tempo)
(add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
#+end_src

** Org-roam
   #+begin_src emacs-lisp
		 (setq org-roam-v2-ack t)
	    (when (file-exists-p "~/org-roam")
		 (setq org-roam-directory "~/org-roam"))
		 (global-set-key "\C-cnl" 'org-roam-buffer-toggle)
		 (global-set-key "\C-cnf" 'org-roam-node-find)
		 (global-set-key "\C-cng" 'org-roam-graph)
		 (global-set-key "\C-cni" 'org-roam-node-insert)
		 (global-set-key "\C-cnc" 'org-roam-capture)
		 ;; Dailies
		 (global-set-key "\C-cnj" 'org-roam-dailies-capture-today)
	    (when (file-exists-p "~/org-roam")
	      (org-roam-db-autosync-mode)
	      	    (org-roam-setup))

   #+end_src
** Org-static-blog
   Publicación de entradas en un blog
   #+begin_src emacs-lisp
(setq org-static-blog-publish-title "Libre como en libertad")
(setq org-static-blog-publish-url "http://192.168.1.125/publish/")
(setq org-static-blog-publish-directory "~/blog/")
(setq org-static-blog-posts-directory "~/blog/posts")
(setq org-static-blog-drafts-directory "~/blog/drafts")
(setq org-static-blog-enable-tags t)
(setq org-export-with-toc nil)
(setq org-export-with-section-numbers nil)


(setq org-static-blog-page-header
"<meta name=\"author\" content=\"Carlos Pajuelo\">
<meta name=\"referrer\" content=\"no-referrer\">
<link href= \"static/style.css\" rel=\"stylesheet\" type=\"text/css\" />
<link rel=\"icon\" href=\"static/favicon.ico\">
<link rel=\"apple-touch-icon-precomposed\" href=\"static/favicon-152.png\">
<link rel=\"msapplication-TitleImage\" href=\"static/favicon-144.png\">
<link rel=\"msapplication-TitleColor\" href=\"#0141ff\">
<script src=\"static/katex.min.js\"></script>
<script src=\"static/auto-render.min.js\"></script>
<link rel=\"stylesheet\" href=\"static/katex.min.css\">
<script>document.addEventListener(\"DOMContentLoaded\", function() { renderMathInElement(document.body); });</script>
<meta http-equiv=\"content-type\" content=\"application/xhtml+xml; charset=UTF-8\">
<meta name=\"viewport\" content=\"initial-scale=1,width=device-width,minimum-scale=1\">")

(setq org-static-blog-page-preamble
"<div class=\"header\">
  <a href=\"https://192.168.1.125\">Blog sobre software libre</a>
  <div class=\"sitelinks\">
    <a href=\"https://gitlab.com/gnuhack\">Gitlab</a> | <a href=\"https://github.com/gnuhack\">Github</a>
  </div>
</div>")

(setq org-static-blog-page-postamble
"<div id=\"archive\">
  <a href=\"https://192.168.1.125/archive.html\">Other posts</a>
</div>

<center><a rel=\"license\" href=\"https://creativecommons.org/licenses/by-sa/3.0/\"><img alt=\"Creative Commons License\" style=\"border-width:0\" src=\"https://i.creativecommons.org/l/by-sa/3.0/88x31.png\" /></a><br /><span xmlns:dct=\"https://purl.org/dc/terms/\" href=\"https://purl.org/dc/dcmitype/Text\" property=\"dct:title\" rel=\"dct:type\">192.168.1.125</span> by <a xmlns:cc=\"https://creativecommons.org/ns#\" href=\"https://192.168.1.125\" property=\"cc:attributionName\" rel=\"cc:attributionURL\">Carlos Pajuelo</a> is licensed under a <a rel=\"license\" href=\"https://creativecommons.org/licenses/by-sa/3.0/\">Creative Commons Attribution-ShareAlike 3.0 Unported License</a>.</center>")

   #+end_src>
** Org-pomodoro
   Ténica de trabajo con descansos cortos. https://github.com/marcinkoziej/org-pomodoro
   #+begin_src emacs-lisp
     ;; Sonido de https://freesound.org/people/.Andre_Onate/sounds/484665/
     (setq org-clock-sound "~/Descargas/ding.wav")
     ;; Para iniciar el crono, pulsar C-c C-x ;
     (setq org-timer-default-timer "00:25:00")
   #+end_src
** Org-agenda
   Vacaciones del curso 2021-2022
   #+begin_src emacs-lisp
	  (setq holiday-other-holidays '((holiday-fixed 10 12 "Día de mi Españita")
					 (holiday-fixed 12 23 "Navidad")
					 (holiday-fixed 12 24 "Navidad")
					 (holiday-fixed 11 01 "Día de todos los santos")
					 (holiday-fixed 12 06 "Día de la Constitución")
					 (holiday-fixed 12 08 "Festividad de la Imnaculada")
					 (holiday-fixed 01 28 "Santo Tomás de Aquino (Aquí no, aquí no...)")
					 (holiday-fixed 02 28 "Día del Glorious Anthem of Andalusia")
					 (holiday-fixed 05 02 "Día del trabajo")
					 (holiday-fixed 05 04 "Fiesta local")
					 (holiday-fixed 06 16 "Corpus Christi")))

     (setq holiday-general-holidays nil)
     (setq holiday-local-holidays nil)
     (setq holiday-solar-holidays nil)
     (setq holiday-bahai-holidays nil)
     (setq holiday-christian-holidays nil)
     (setq holiday-hebrew-holidays nil)
     (setq holiday-islamic-holidays nil)
     (setq holiday-oriental-holidays nil)
   #+end_src
* Recentf
  Con recentf-mode se puede acceder fácilmente a los ficheros usados más recientemente, y también a los [[*Entorno del editor][búferes]]
  #+begin_src emacs-lisp
    (recentf-mode)
  #+end_src
* Notificaciones
Funciones para que las notificaciones de la agenda me lleguen al escritorio con espeak. Además del código de abajo hace falta meter en ~/bin un appt-notification con lo siguiente:
#+BEGIN_SRC 
#!/bin/sh

TIME="$1"
MSG="$2"

notify-send -t 0 "Appointment in $TIME minutes:$MSG"
espeak "Appointment in $TIME minutes: $MSG"

#+END_SRC
Aquí están las funciones para la notificación.
#+BEGIN_SRC emacs-lisp
  (require 'appt)
  (appt-activate t)

  (setq appt-message-warning-time 30) ; Show notification 30 minutes before event
  (setq appt-display-interval appt-message-warning-time) ; Disable multiple reminders
  (setq appt-display-mode-line nil)

  ; Use appointment data from org-mode
  (defun my-org-agenda-to-appt ()
    (interactive)
    (setq appt-time-msg-list nil)
    (org-agenda-to-appt))

  ; Update alarms when...
  ; (1) ... Starting Emacs
  (when (file-exists-p "~/org")
    (my-org-agenda-to-appt))

  ; (2) ... Everyday at 12:05am (useful in case you keep Emacs always on)
  (when (file-exists-p "~/org")
    (run-at-time "12:05am" (* 24 3600) 'my-org-agenda-to-appt))

  ; (3) ... When TODO.txt is saved
  (when (file-exists-p "~/org")
    (add-hook 'after-save-hook
	    '(lambda ()
	       (if (string= (buffer-file-name) (concat (getenv "HOME") "/ideas/TODO.txt"))
		   (my-org-agenda-to-appt)))))

  ; Display appointments as a window manager notification
  (setq appt-disp-window-function 'my-appt-display)
  (setq appt-delete-window-function (lambda () t))

  (setq my-appt-notification-app (concat (getenv "HOME") "/bin/appt-notification"))

  (defun my-appt-display (min-to-app new-time msg)
    (if (atom min-to-app)
      (start-process "my-appt-notification-app" nil my-appt-notification-app min-to-app msg)
    (dolist (i (number-sequence 0 (1- (length min-to-app))))
      (start-process "my-appt-notification-app" nil my-appt-notification-app (nth i min-to-app) (nth i msg)))))
#+END_SRC
* PDF
Macro para poner el modo noche en los pdfs (modonoche) y funciones para conseguir un marcapáginas en un pdf. Sacado de https://sachachua.com/blog/2021/02/guest-post-bookmarking-pdfs-in-emacs-with-pdf-tools-and-registers/
#+BEGIN_SRC emacs-lisp

  (fset 'modonoche
	(lambda (&optional arg) "Keyboard macro." (interactive "p") (kmacro-exec-ring-item (quote ("m" 0 "%d")) arg)))
  (add-hook 'pdf-view-mode-hook (lambda() (nlinum-mode -1))) ;;Desactivar linum mode, que no va bien con pdf-view-mode
  (pdf-tools-install)

  (define-key pdf-view-mode-map (kbd "<C-f1>")
    (lambda ()
      "Saves the current position on the pdf to jump to later with <C-f2>."
      (interactive)
      (setf my-bookmark (pdf-view-bookmark-make-record))
      (message "Posición guardada")
  ))

  (define-key pdf-view-mode-map (kbd "<C-f2>")
    (lambda ()
      "Loads the position saved by <C-f1>."
      (interactive)
      (pdf-view-bookmark-jump my-bookmark)
      (message "Posición cargada")
  ))

#+END_SRC
* Elfeed
Con elfeed puedo tener mi propio feed personalizado. Sobre todo es útil para seguir blogs individuales que no tengan una alta frecuencia de posteo. También me sirve para "suscribirme" a canales de Youtube sin visitar la página, gracias as la función definida abajo. He quitado la parte de =emacs-lisp= al lado de #+BEGIN_SRC para que no se evalúe este código, ya que ahora se encarga de elfeed el fichero init.el.
#+BEGIN_SRC
(global-set-key (kbd "C-x w") 'elfeed)
(setq elfeed-feeds
 (quote
  (("https://videos.lukesmith.xyz/feeds/videos.xml?sort=-publishedAt&filter=local" Video)
   ("https://www.youtube.com/feeds/videos.xml?channel_id=UCaifrB5IrvGNPJmPeVOcqBA" Kruggsmash Video)
   ("https://www.bay12games.com/dwarves/dev_now.rss" Dwarf Fortress Video)
   ("https://www.youtube.com/feeds/videos.xml?channel_id=UCD6VugMZKRhSyzWEWA9W2fg" Video)
   ("https://www.youtube.com/feeds/videos.xml?channel_id=UC2eYFnH61tmytImy1mTYvhA" Video)
   ("http://planet.emacs-es.org/rss20.xml" Emacs)
   ("http://karl-voit.at/feeds/lazyblorg-all.atom_1.0.links-and-content.xml" Blog)
   ("https://planet.emacslife.com/atom.xml" Emacs)
   ("https://blog.mobian-project.org/index.xml" Blog)
   ("https://twobithistory.org/feed.xml" Blog))))
#+END_SRC
Con la siguiente función puedo reproducir vídeos de Youtube en mpv descargándolos con youtube-dl. Solo hay que ponerse sobre el link de Youtube y hacer =M-x std::elfeed::visit-entry-dwim=
#+BEGIN_SRC emacs-lisp

(defun std::elfeed::visit-entry-dwim (&optional arg)
  "Función para reproducir vídeos en elfeed de Youtube con mpv ARG."
  (interactive "P")
  (if arg
      (elfeed-search-browse-url)
    (-let [entry (if (eq major-mode 'elfeed-show-mode) elfeed-show-entry (elfeed-search-selected :single))]
      (if (s-matches? (rx "https://www.youtube.com/watch" (1+ any))
                      (elfeed-entry-link entry))
          (let* ((quality (completing-read "Max height resolution (0 for unlimited): " '("0" "480" "720" "1080")))
                 (format (if (= 0 (string-to-number quality)) "" (format "--ytdl-format=[height<=?%s]" quality))))
            (message "Opening %s with height ≤ %s with mpv..."
                     (elfeed-entry-link entry) quality)
            (elfeed-untag entry 'unread)
            (start-process "elfeed-mpv" nil "mpv" format (elfeed-entry-link entry))
            (elfeed-search-update :force))
        (if (eq major-mode 'elfeed-search-mode)
            (elfeed-search-browse-url)
          (elfeed-show-visit))))))
#+END_SRC
* EMMS
Para reproducir música he elegido emms, que es bastante simple de configurar. Para que se carguen los datos en caché la primera vez que use emms hay que añadir a la lista de reproducción la carpeta de música que quiera reproducir (con add-directory-tree) y luego ya iniciarlo con emms-start.
#+BEGIN_SRC emacs-lisp
  ;;emms
  (require 'emms-setup)
  (emms-all)
  (emms-default-players)
  (setq emms-source-file-default-directory "~/Música/")
  (require 'emms-history)
  (emms-history-load)
  (emms-mode-line-disable)
  (global-set-key (kbd "<XF86AudioPrev>") 'emms-previous)
  (global-set-key (kbd "<XF86AudioNext>") 'emms-next)
  (global-set-key (kbd "<XF86AudioPlay>") 'emms-pause)
  (global-set-key (kbd "<XF86MonBrightnessUp>") 'emms-shuffle) 
  (global-set-key (kbd "s-m") 'notmuch)
  (add-hook 'emms-mode-hook 'hl-line-mode)
  (add-hook 'emms-mode-hook 'visual-line-mode)
  
#+END_SRC
* Keybindings
Atajos de teclas y registros.
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-x w") 'elfeed)
  (global-set-key (kbd "C-<tab>") 'rat/sigtel)
  (global-set-key (kbd "C-<iso-lefttab>") 'rat/anttel)
  (global-set-key (kbd "C-x p") 'proced)
  (global-set-key (kbd "C-x e") 'eshell)
  (global-set-key (kbd "C-c y") 'clipboard-yank)
  (global-set-key (kbd "C-x t") 'term)
  (global-set-key (kbd "C-c m") 'calendar)
  (global-set-key (kbd "M-o") 'other-window)
  (global-set-key (kbd "s-o") 'other-window)
  (global-set-key (kbd "C-x k") 'kill-current-buffer)
  (global-set-key (kbd "<f5>") 'modonoche)
  (add-to-list 'org-file-apps '("pdf" . "evince %s"))
  (global-set-key (kbd "<f6>") 'quick-calc)
  (set-register ?o (cons 'file "/home/carlos/Nextcloud/Documents/horario.txt"))
  (set-register ?e (cons 'file "/home/carlos/git/dotfiles/.emacs.d/emacs-literario.org"))
  (set-register ?t (cons 'file "/home/carlos/org/2021t/tiempo.org"))
  (global-set-key (kbd "s-n") 'next-buffer)
  (global-set-key (kbd "s-p") 'previous-buffer)
  (global-set-key (kbd "s-<backspace>") 'rat/killydelete)
  (global-set-key (kbd "s-<return>") 'rat/terminal)
#+END_SRC
* Projectile
Para gestionar proyectos he elegido proyectile. Así puedo cambiar entre archivos de un proyecto de forma fácil y cómoda. Un proyecto es toda carpeta que contenga archivos clave (como los repos de git).
#+BEGIN_SRC emacs-lisp
(projectile-mode +1)
(define-key projectile-mode-map (kbd "C-c p") 'projectile-command-map)
#+END_SRC
* Telega
Cliente de Telegram para Emacs.
#+BEGIN_SRC emacs-lisp
  (setq emojify-emoji-styles '(unicode))
  (global-set-key (kbd "s-T") 'telega)
  (global-set-key (kbd "s-i") 'emojify-insert-emoji)
  (define-key global-map (kbd "C-c t") telega-prefix-map)
  (add-hook 'telega-load-hook 'telega-notifications-mode)
  (setq telega-chat-fill-column 16)
  ;;(add-hook 'telega-load-hook 'emoji-mode)
  (add-hook 'after-init-hook #'global-emojify-mode)
  (add-hook 'telega-chat-mode-hook 'variable-pitch-mode)
  (add-hook 'telega-root-mode-hook 'hl-line-mode)
#+END_SRC
* Guardado
Guarda el estado de un búfer cuando se cierra éste o Emacs.
#+BEGIN_SRC emacs-lisp
(save-place-mode 1)
#+END_SRC
* Correo
Configuración copiada de mi antiguo .emacs.el de cuando usaba Prelude y GNUS. Para los contactos uso EBDB. (https://chrisdone.com/posts/emacs-mail/)
#+begin_src emacs-lisp
	(require 'ebdb-message) ;;Cargar la ebdb con los contactos
     ;;   (setq send-mail-function 'smtpmail-send-it)
     ;;   (setq smtpmail-smtp-user   "nkolita1")
     ;;   (setq smtpmail-smtp-server "smtp.gmail.com")
     ;;   (setq smtpmail-smtp-service 587)
	(setq gnus-select-method
	      '(nnmaildir "GMail"
			  (directory "~/Test")
			  (directory-files nnheader-directory-files-safe)
			  (get-new-mail nil)))

     ;;   (setq message-send-mail-function   'smtpmail-send-it
     ;;	 smtpmail-default-smtp-server "smtp.gmail.com"
     ;;	 smtpmail-smtp-server         "smtp.gmail.com"
     ;;	 smtpmail-local-domain        "mail.google.com")

	;; Por fin he conseguido enviar correos con hotmail

     ;; (setq message-send-mail-function 'smtpmail-send-it
     ;; 	   smtpmail-stream-type 'starttls
     ;; 	   smtpmail-default-smtp-server "smtp.office365.com"
     ;; 	   smtpmail-smtp-server "smtp.office365.com"
     ;; 	   smtpmail-smtp-service 587
     ;; 	   smtpmail-smtp-user "carlospajuelo_@hotmail.com"
     ;; 	   ;; account info
     ;; 	   user-mail-address "carlospajuelo_@hotmail.com"
     ;; 	   user-full-name  "Carlos Pajuelo")

  ;; Y con mi cuenta personal también!!

    (setq message-send-mail-function 'smtpmail-send-it
	    smtpmail-stream-type 'starttls
	    smtpmail-default-smtp-server "smtp.pajuelo.com"
	    smtpmail-smtp-server "smtp.pajuelo.com"
	    smtpmail-smtp-service 587
	    smtpmail-smtp-user "carlos@pajuelo.com"
	    ;; account info
	    user-mail-address "carlos@pajuelo.com"
	    user-full-name  "Carlos")

	(defun offlineimap ()
	  "Función para ejecutar offlineimap y descargar el correo en gnus."
	  (interactive)
	  (shell-command "offlineimap&" "*offlineimap*" nil)
	  )
#+end_src
* Diccionario
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-c d") #'dictionary-search)
(setq dictionary-server "dict.org")

#+END_SRC

* Ledger
  Ledger es una herramienta para llevar la contabilidad. Hledger es el port a Haskell de Ledger. Setup básico de la página oficial https://github.com/narendraj9/hledger-mode:
  #+begin_src emacs-lisp
     ;;; Basic configuration
     (require 'hledger-mode)

     ;; To open files with .dat extension in hledger-mode
     (add-to-list 'auto-mode-alist '("\\.dat\\'" . hledger-mode))

     ;; Provide the path to you journal file.
     ;; The default location is too opinionated.
     (setq hledger-jfile "~/Documentos/cuentas.dat")
     (setq hledger-currency-string "€")


     ;;; Auto-completion for account names
     ;; For company-mode users,
    ;;(add-to-list 'company-backends 'hledger-company)
    ;; Keybindings
    (global-set-key (kbd "C-c e") 'hledger-jentry)
    (global-set-key (kbd "C-c j") 'hledger-run-command)
    (add-hook 'hledger-jentry-hook 'hledger-time )
  #+end_src

* Helm
  Dado que ido parece que no funciona en todas partes (por ejemplo al cambiar de nodo en org-roam), voy a probar con helm a ver cómo me va. Para empezar sólo voy a poner la configuración mínima, mi idea es coger el código de http://tuhdo.github.io/helm-intro.html ya que es la configuración que usaba cuando tenía Prelude instalado.
  #+begin_src emacs-lisp
    (require 'helm-config)
    (helm-mode 1)
    (global-set-key (kbd "M-x") 'helm-M-x)
  #+end_src

* Engine mode
  Con el engine-mode se puede usar Emacs como interfaz de motores de búsqueda.
  #+begin_src emacs-lisp
(engine-mode 1)
(setq engine/browser-function 'eww-browse-url)
(engine/set-keymap-prefix (kbd "C-c w"))

(defengine duckduckgo
  "https://duckduckgo.com/?q=%s"
  :keybinding "d")
(defengine wikipedia
  "http://www.wikipedia.org/search-redirect.php?language=en&go=Go&search=%s"
  :keybinding "w"
  :docstring "Searchin' the wikis.")

  #+end_src

